import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LoginPage</Link>
        </li>
        <li>
          <Link to="/createclient">CreateClient</Link>
        </li>
        <li>
          <Link to="/behaviourdata">BehaviourData</Link>
        </li>
        <li>
          <Link to="/sessionviewprogramtemplate">
            SessionViewProgramTemplate
          </Link>
        </li>
        <li>
          <Link to="/addclienttopractitioner">AddClienttoPractitioner</Link>
        </li>
        <li>
          <Link to="/homepagepatients">Homepagepatients</Link>
        </li>
        <li>
          <Link to="/childdashboard">ChildDashboard</Link>
        </li>
        <li>
          <Link to="/programsnoneopen">ProgramsNoneOpen</Link>
        </li>
        <li>
          <Link to="/sessiondatacollectioncoldprobe">
            SessionDataCollectionColdProbe
          </Link>
        </li>
        <li>
          <Link to="/forgotpasswordpage">ForgotPasswordPage</Link>
        </li>
        <li>
          <Link to="/programsdropdown">ProgramsDropdown</Link>
        </li>
        <li>
          <Link to="/programhistorypageprogramtemplate">
            ProgramHistoryPageProgramTemplate
          </Link>
        </li>
        <li>
          <Link to="/sessiondatacollectionmasstrial">
            SessionDataCollectionMassTrial
          </Link>
        </li>
        <li>
          <Link to="/sessionbehaviouraldata">SessionBehaviouralData</Link>
        </li>
        <li>
          <Link to="/behaviordatahistory">BehaviorDataHistory</Link>
        </li>
        <li>
          <Link to="/passwordrequestedpage">PasswordRequestedPage</Link>
        </li>
        <li>
          <Link to="/programsdropdownopen">ProgramsDropdownOpen</Link>
        </li>
        <li>
          <Link to="/programhistorypagetrial">ProgramHistoryPageTrial</Link>
        </li>
        <li>
          <Link to="/programdetailsentry">ProgramDetailsEntry</Link>
        </li>
        <li>
          <Link to="/programdetailsentrycoldprobe">
            ProgramDetailsEntryColdProbe
          </Link>
        </li>
        <li>
          <Link to="/programdetailsentrymasstrial">
            ProgramDetailsEntryMassTrial
          </Link>
        </li>
        <li>
          <Link to="/programdetailsentrycoldprobetargets">
            ProgramDetailsEntryColdProbeTargets
          </Link>
        </li>
        <li>
          <Link to="/programdetailsentrymasstrialtargets">
            ProgramDetailsEntryMassTrialTargets
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
